# Generated by Django 4.2.5 on 2023-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_publicstatements_school_publicstatements_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
