# Generated by Django 4.2.5 on 2023-11-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teacher_is_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='School',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_grade', models.IntegerField(blank=True, null=True)),
                ('second_grade', models.IntegerField(blank=True, null=True)),
                ('last_grade', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
