# Generated by Django 4.2.5 on 2023-11-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_school_grade'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
    ]
