# Generated by Django 4.2.5 on 2023-11-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_customuser_address_remove_customuser_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
